/gridbot/grid_processor:
  ros__parameters:
    # camera_topic: "camera/image_rect/compressed"
    camera_topic: "camera/image_raw/compressed"
    line_offset_topic: "line_offset"
    tracked_image_topic: "camera/image_tracked/compressed"
    aruco_topic: "aruco"
    line_turning_topic: "line_turning"

    quantize_div: 64

    line_color: [120, 40, 40]

    h_thresh_low: 25
    h_thresh_high: 25
    s_low: 100
    s_high: 220
    v_low: 50
    v_high: 200

    line_roi_height: 0.6
    center_line_roi_width: 0.2
    sides_line_roi_width: 0.3

    aruco_roi_width: 0.8
    aruco_roi_height: 1.0

    line_turning_threshold: 0.5

    aruco_padding: 25
    
    midline_step: 30
    followed_node_offset: 3

    prepare_tracked_image: true
