/gridbot/map_generator:
  ros__parameters:
    yaml_save_path: "ros2_ws/src/gridbot/config/map_graph.yaml"
    img_save_path: "ros2_ws/src/gridbot/sim_assets/models/grid/map_grid.png"
    img_width: 4096
    img_height: 4096
    tag_size: 300
    text_size: 100
    line_color: [0, 0, 255]
    line_length: 450
    line_thickness: 30
    padding: 1000
    text_padding: 100

    graph_width: 3
    graph_height: 2

    removed_nodes:
      - ""

    edges:

      # 2x3 test
      # row1:
      - "A1,B1,1"
      - "B1,C1,1"
      # row2:
      - "A2,B2,1"
      - "B2,C2,1"
      # col1:
      - "A1,A2,1"
      # col2:
      - "B1,B2,1"
      # col3:
      - "C1,C2,1" 


      # Horizontal
      # Row 1
        


      # - "A1,B1,6"
      # - "B1,C1,3"
      # - "C1,D1,8"

      # # Row 2
      # - "A2,B2,4"
      # - "B2,C2,9"
      # - "C2,D2,2"

      # # Row 3
      # - "A3,B3,5"
      # - "B3,D3,8"
      
      # # Vertical
      # # Column A
      # - "A1,A2,3"
      # - "A2,A3,5"

      # # Column B
      # - "B1,B2,7"
      # - "B2,B3,2"

      # # Column C
      # - "C1,C2,5"
      # - "C2,C3,6"

      # # Column D
      # - "D1,D2,4"
      # - "D2,D3,9"