/gridbot/motor_driver:
  ros__parameters:
    twist_topic: "cmd_vel"

    left_enable_pin: 6
    left_forward_pin: 12
    left_backward_pin: 13

    right_enable_pin: 26
    right_forward_pin: 20
    right_backward_pin: 21

    wheel_radius: 0.021
    wheel_separation: 0.08382

    vel_multiplier: 0.18

    frequency: 50.0

    invert_direction: true
